# resolver: lts-8.24
# resolver: ghc-8.10.2
# resolver: lts-17.9
# resolver: ghc-8.8.3
resolver: lts-23.1 #https://www.stackage.org/lts-23.1
packages:
  - atcoder/beginner/q085
  - atcoder/beginner/q086
  - atcoder/beginner/q110
  - atcoder/beginner/q111
  - atcoder/beginner/q165
  - atcoder/dp
  # - topcoder
# extra-deps:
#   - HDBC-sqlite3-2.3.3.1
