resolver: lts-23.2

packages:
  - src/topcoder
  - src/atcoder/beginner111
  - src/atcoder/beginner422
  - src/atcoder/dp
  # - src/util

extra-deps: []

flags: {}

extra-package-dbs: []

# GHC options
ghc-options:
  "$everything": -Wall

# ビルド結果出力先
work-dir: ./.stack-work