version: "3.8"
services:
  
  dev-haskell: &dev-rust-settings
    image: dev-rust
    container_name: dev-rust
    ports:
      - "22:22"
    volumes:
      - "./.vscode:/root/.vscode"
      - "./.vscode-server:/root/.vscode-server"
      - "./src:/root/src"
      - "./Cargo.toml:/root/Cargo.toml"